import type { Gig, GigDraft } from "./types";
import type { TranslationKey } from "./i18n";
import {
  CATEGORIES,
  CATEGORY_LABELS,
  categoryColors,
  glyphForCategory,
  isAllowedCategory,
  isAllowedSkill,
  normalizeSkills,
} from "./taxonomy";

/* Category metadata is derived from the taxonomy module so there is a single
   source of truth. Re-exported under the original names for existing callers. */
export const CATEGORY_OPTIONS: string[] = CATEGORY_LABELS;

export const CATEGORY_GLYPHS: Record<string, string> = Object.fromEntries(
  CATEGORIES.map((category) => [category.label, category.glyph]),
);

export const CATEGORY_LABEL_KEYS: Record<string, TranslationKey> = Object.fromEntries(
  CATEGORIES.map((category) => [category.label, category.translationKey]),
);

export function glyphFor(category: string): string {
  return glyphForCategory(category);
}

export function isCategory(value: string): boolean {
  return isAllowedCategory(value);
}

export const SEED_GIGS: Gig[] = [
  {
    id: "seed-01",
    title: "Full-Stack Web Application Development with React & Node",
    description:
      "End-to-end product engineering: architecture, responsive UI, secure APIs, database design, testing and deployment.",
    seller: "Aisha Rahman",
    role: "Top Rated Seller",
    verified: true,
    rating: 4.9,
    reviews: 412,
    price: 450,
    delivery: "5 days",
    category: "Web Development",
    skills: ["Full-Stack Development", "React", "Node.js", "PostgreSQL", "REST APIs"],
    badge: "Top Rated",
    colors: categoryColors("Web Development"),
    glyph: glyphForCategory("Web Development"),
    video: "/videos/developer.mp4",
    videoName: "Full-stack build demo",
  },
  {
    id: "seed-02",
    title: "Complete Modern UI/UX Design System in Figma",
    description:
      "Research-backed interface design with reusable components, tokens, accessibility checks and a handoff-ready Figma file.",
    seller: "Marco Bianchi",
    role: "Level 2 Seller",
    verified: true,
    rating: 5,
    reviews: 288,
    price: 320,
    delivery: "3 days",
    category: "UI/UX Design",
    skills: ["UI Design", "Design Systems", "Figma", "Prototyping", "Accessibility"],
    badge: "Pro",
    colors: categoryColors("UI/UX Design"),
    glyph: glyphForCategory("UI/UX Design"),
  },
  {
    id: "seed-03",
    title: "SEO & Performance Website Optimization",
    description:
      "Keyword research, technical SEO fixes, content roadmap and conversion tracking to grow qualified organic traffic.",
    seller: "Linda Okafor",
    role: "Top Rated Seller",
    verified: true,
    rating: 4.8,
    reviews: 531,
    price: 260,
    delivery: "7 days",
    category: "Paid Marketing",
    skills: ["SEO", "Content Marketing", "Google Analytics", "Conversion Optimization (CRO)"],
    badge: "Best Seller",
    colors: categoryColors("Paid Marketing"),
    glyph: glyphForCategory("Paid Marketing"),
  },
  {
    id: "seed-04",
    title: "Cinematic Video Editing & Color Grading for Brands",
    description:
      "Story-driven editing, motion graphics, sound design and broadcast-grade color grading for ads and social campaigns.",
    seller: "Daniel Cruz",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.9,
    reviews: 194,
    price: 180,
    delivery: "4 days",
    category: "Video Production",
    skills: ["Video Editing", "Color Grading", "Motion Graphics", "Sound Design"],
    badge: "Pro",
    colors: categoryColors("Video Production"),
    glyph: glyphForCategory("Video Production"),
    video: "/videos/showcase-1.mp4",
    videoName: "Cinematic reel",
  },
  {
    id: "seed-05",
    title: "Custom AI & Machine Learning Model Development",
    description:
      "Data preparation, model training, evaluation and deployment with clear documentation and reproducible pipelines.",
    seller: "Dr. Priya Nair",
    role: "Top Rated Seller",
    verified: true,
    rating: 5,
    reviews: 137,
    price: 900,
    delivery: "10 days",
    category: "AI Agents",
    skills: ["Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "Data Science"],
    badge: "Top Rated",
    colors: categoryColors("AI Agents"),
    glyph: glyphForCategory("AI Agents"),
  },
  {
    id: "seed-06",
    title: "SEO-Optimized Website Content & Technical Copywriting",
    description:
      "Original, well-researched long-form content structured for search intent, readability and measurable rankings.",
    seller: "Emma Lindqvist",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.8,
    reviews: 276,
    price: 120,
    delivery: "2 days",
    category: "Writing & Copywriting",
    skills: ["SEO Writing", "Blog Writing", "Technical Writing", "Content Writing"],
    badge: "Best Seller",
    colors: categoryColors("Writing & Copywriting"),
    glyph: glyphForCategory("Writing & Copywriting"),
  },
  {
    id: "seed-07",
    title: "E-Commerce Store Development on Shopify & WooCommerce",
    description:
      "Conversion-focused storefronts with product setup, payment and shipping integration, speed tuning and analytics.",
    seller: "Tom Andersen",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.7,
    reviews: 356,
    price: 390,
    delivery: "6 days",
    category: "Web Development",
    skills: ["Shopify", "WordPress", "Full-Stack Development", "API Integration"],
    badge: "Pro",
    colors: categoryColors("Web Development"),
    glyph: glyphForCategory("Web Development"),
    video: "/videos/ecommerce.mp4",
    videoName: "Store walkthrough",
  },
  {
    id: "seed-08",
    title: "Mobile App UI Design for iOS & Android",
    description:
      "Platform-aware mobile interfaces with prototypes, design tokens and developer-ready specs for both app stores.",
    seller: "Sofia Petrova",
    role: "Top Rated Seller",
    verified: true,
    rating: 4.9,
    reviews: 221,
    price: 420,
    delivery: "5 days",
    category: "UI/UX Design",
    skills: ["Mobile App Design", "UI Design", "Prototyping", "Figma"],
    badge: "Best Seller",
    colors: categoryColors("UI/UX Design"),
    glyph: glyphForCategory("UI/UX Design"),
  },
  {
    id: "seed-09",
    title: "Professional YouTube & Short-Form Video Production",
    description:
      "Scripted edits with captions, hooks, thumbnails and pacing tailored for retention on YouTube, Reels and TikTok.",
    seller: "Nadia Haddad",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.9,
    reviews: 302,
    price: 210,
    delivery: "3 days",
    category: "Video Production",
    skills: [
      "Video Editing",
      "YouTube Video Editing",
      "Short-Form / Reels Editing",
      "CapCut",
    ],
    badge: "Pro",
    colors: categoryColors("Video Production"),
    glyph: glyphForCategory("Video Production"),
    video: "/videos/showcase-2.mp4",
    videoName: "Short-form reel",
  },
  {
    id: "seed-10",
    title: "NLP Chatbot & LLM Integration for Your Business",
    description:
      "Custom retrieval pipelines, prompt engineering and API integration to deploy reliable assistants on your data.",
    seller: "Kevin Zhao",
    role: "Top Rated Seller",
    verified: true,
    rating: 5,
    reviews: 96,
    price: 750,
    delivery: "8 days",
    category: "AI Agents",
    skills: [
      "LLM Integration",
      "Chatbot Development",
      "NLP",
      "Prompt Engineering",
      "OpenAI API",
    ],
    badge: "Top Rated",
    colors: categoryColors("AI Agents"),
    glyph: glyphForCategory("AI Agents"),
  },
  {
    id: "seed-11",
    title: "Landing Page UI Design & Conversion Optimization",
    description:
      "High-converting landing pages with wireframes, responsive UI, A/B test variants and a developer-ready handoff.",
    seller: "James Whitfield",
    role: "Level 1 Seller",
    verified: false,
    rating: 4.8,
    reviews: 168,
    price: 150,
    delivery: "7 days",
    category: "UI/UX Design",
    skills: ["Landing Page Design", "Web Design", "UI Design", "Wireframing"],
    badge: "Rising Talent",
    colors: categoryColors("UI/UX Design"),
    glyph: glyphForCategory("UI/UX Design"),
  },
  {
    id: "seed-12",
    title: "AI Workflow Automation & Custom Chatbot Setup",
    description:
      "Automate repetitive business workflows and deploy a custom chatbot trained on your own documents and data.",
    seller: "Grace Mensah",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.9,
    reviews: 143,
    price: 220,
    delivery: "4 days",
    category: "AI Agents",
    skills: ["AI Automation", "Workflow Automation", "Chatbot Development", "Zapier"],
    badge: "Pro",
    colors: categoryColors("AI Agents"),
    glyph: glyphForCategory("AI Agents"),
  },
  {
    id: "seed-13",
    title: "Brand Identity, Logo & Complete Visual Guidelines",
    description:
      "A full brand system: logo suite, colour and type scales, usage rules and ready-to-use marketing assets.",
    seller: "Ana Ferreira",
    role: "Top Rated Seller",
    verified: true,
    rating: 4.9,
    reviews: 264,
    price: 340,
    delivery: "6 days",
    category: "Graphic Design & Branding",
    skills: ["Brand Identity", "Logo Design", "Brand Guidelines", "Visual Identity"],
    badge: "Top Rated",
    colors: categoryColors("Graphic Design & Branding"),
    glyph: glyphForCategory("Graphic Design & Branding"),
  },
  {
    id: "seed-14",
    title: "Meta & Google Ads Campaign Management for Growth",
    description:
      "Audience research, creative testing, budget pacing and conversion tracking to lower cost per acquisition.",
    seller: "Owen Bennett",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.8,
    reviews: 187,
    price: 300,
    delivery: "5 days",
    category: "Paid Marketing",
    skills: ["Meta Ads", "Google Ads", "Campaign Management", "Conversion Optimization (CRO)"],
    badge: "Pro",
    colors: categoryColors("Paid Marketing"),
    glyph: glyphForCategory("Paid Marketing"),
  },
  {
    id: "seed-15",
    title: "Cross-Platform Mobile App Development (React Native / Flutter)",
    description:
      "Production-ready iOS and Android apps from a single codebase, with API integration, testing and store submission.",
    seller: "Hiroshi Tanaka",
    role: "Top Rated Seller",
    verified: true,
    rating: 4.9,
    reviews: 158,
    price: 680,
    delivery: "9 days",
    category: "Mobile App Development",
    skills: ["React Native", "Flutter", "Cross-Platform Apps", "Mobile App Development"],
    badge: "Top Rated",
    colors: categoryColors("Mobile App Development"),
    glyph: glyphForCategory("Mobile App Development"),
  },
  {
    id: "seed-16",
    title: "Professional Website, Ad & Email Copywriting",
    description:
      "Persuasive, on-brand copy for landing pages, ad campaigns and email sequences that turns readers into customers.",
    seller: "Chloe Martin",
    role: "Level 2 Seller",
    verified: true,
    rating: 4.9,
    reviews: 209,
    price: 140,
    delivery: "3 days",
    category: "Writing & Copywriting",
    skills: ["Professional Copywriting", "Ad Copy", "Email Copywriting", "Website Copy"],
    badge: "Best Seller",
    colors: categoryColors("Writing & Copywriting"),
    glyph: glyphForCategory("Writing & Copywriting"),
  },
].map((gig) => ({
  ...gig,
  // Guard the seed data against typos — only allowed skills survive.
  skills: normalizeSkills(gig.skills, gig.category),
}));

export function createGig(draft: GigDraft): Gig {
  const days = draft.deliveryDays;
  const category = isAllowedCategory(draft.category) ? draft.category : CATEGORY_OPTIONS[0];
  return {
    id:
      typeof crypto !== "undefined" && "randomUUID" in crypto
        ? crypto.randomUUID()
        : `gig-${Date.now()}`,
    title: draft.title,
    description: draft.description,
    seller: draft.seller,
    role: "New Seller",
    verified: false,
    rating: 0,
    reviews: 0,
    price: draft.price,
    delivery: `${days} ${days === 1 ? "day" : "days"}`,
    category,
    skills: normalizeSkills(draft.skills, category),
    badge: "New",
    colors: categoryColors(category),
    glyph: glyphForCategory(category),
    video: draft.video?.trim() || undefined,
    videoName: draft.videoName?.trim() || undefined,
    isNew: true,
  };
}

export { isAllowedSkill };
